### ISSUE TITLE
Lizenz hinzufügen

### ISSUE THREAD

**Issue by cswertz** [cswertz/LehrbuchDigitaleGrundbildung#1]
Benötigt wird eine Lizenz für ein OER (Open Educational Ressources) - Projekt, in dem Material  kooperativ erarbeitet und bearbeitet werden soll. Nach [https://austria-forum.org/af/Unterrichtsmaterialien/Open_Educational_Resources/Lizenzen_f%C3%BCr_OER](OER - Lizenzen von Schön/Ebner) sind CC - Lizenzen gut geeignet. Angemessen erscheint CC-BY-SA. Die Weitergabe unter gleichen Bedigungen ist erforderlich, die Bearbeitung ist möglich.
Die CC-BY-SA 4.0 International - Lizenz wurde von der CreativeCommons-Webseite in die Datei LICENSE kopiert.

**Comment by rschrenk** [comment]
Ich möchte anregen, dass als Lizenz cc-by gewählt wird. Es ist auf den ersten Blick zwar nachvollziehbar, dass man bei Änderungen den Erhalt der Lizenz erzwingen möchte, damit ergeben sich bei einem Remix aber möglicherweise Konflikte zwischen unterschiedlichen Lizenzsystemen (bspw. wenn beide Lizenzen verlangen, dass die eigene bei einem Derivat weiterbenutzt wird).

**Comment by cswertz** [comment]
@rschrenk Danke für den Hinweis. Klingt für mich überzeugend. Da es keine anderen Einschätzungen gab, habe ich die Lizenz geändert.
